import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import MiniSearch from "minisearch";
import { describe, expect, it } from "vitest";
import { firstLetter } from "../db/repository";

// These files are generated by `bun run build-data` and committed. The tests fail
// when `data.json` was edited without regenerating them.
const root = resolve(__dirname, "../../..");
const readJson = (path: string) => JSON.parse(readFileSync(resolve(root, path), "utf-8"));

const source: Array<{ id: string; word?: string; definition?: string; createdBy?: unknown }> =
  readJson("data.json");
const published: Array<{ id: string; word: string; definition: string }> =
  readJson("static/data.json");
const initial = readJson("src/lib/data/initial-words.json");

describe("published data", () => {
  it("contains every source entry exactly once", () => {
    expect(published.length).toBe(source.length);
    expect(new Set(published.map((w) => w.id)).size).toBe(published.length);
    expect(new Set(published.map((w) => w.id))).toEqual(new Set(source.map((w) => w.id)));
  });

  it("carries each source entry's current word and definition", () => {
    const byId = new Map(published.map((w) => [w.id, w]));
    // Legacy entries (no `word` field) are normalized by build-index.ts; compare the rest verbatim.
    const stale = source
      .filter((w) => "word" in w && "createdBy" in w)
      .filter((w) => {
        const out = byId.get(w.id);
        return out?.word !== w.word || out?.definition !== w.definition;
      });
    expect(stale.map((w) => w.id)).toEqual([]);
  });

  it("has a non-empty word and definition for every entry", () => {
    const broken = published.filter((w) => !w.word.trim() || !w.definition.trim());
    expect(broken.map((w) => w.id)).toEqual([]);
  });

  it("indexes every published entry", () => {
    const index = MiniSearch.loadJSON(
      readFileSync(resolve(root, "static/search-index.json"), "utf-8"),
      {
        fields: ["word", "definition"],
        idField: "id",
      }
    );
    expect(index.documentCount).toBe(published.length);
    expect(published.filter((w) => !index.has(w.id)).map((w) => w.id)).toEqual([]);
  });

  it("stores no fields in the index: results are looked up by id in data.json", () => {
    const json = JSON.parse(readFileSync(resolve(root, "static/search-index.json"), "utf-8"));
    expect(Object.keys(json.storedFields ?? {})).toEqual([]);
  });

  it("builds the letter row with the same filing rule the client uses", () => {
    const counts = new Map<string, number>();
    for (const w of published)
      counts.set(firstLetter(w.word), (counts.get(firstLetter(w.word)) ?? 0) + 1);
    const expected = [...counts.keys()]
      .sort((a, b) => a.localeCompare(b, "es"))
      .map((letter) => ({ letter, count: counts.get(letter) }));
    expect(initial.letters).toEqual(expected);
  });

  it("prerenders the same first page the client shows after loading", () => {
    expect(initial.total).toBe(source.length);
    expect(initial.totalPages).toBe(Math.ceil(source.length / initial.pageSize));
    expect(initial.words).toEqual(published.slice(0, initial.pageSize));
  });

  it("builds the first page's pager exactly as the client computes it", async () => {
    const repo = await import("../db/repository");
    repo.seedWords(published as never);
    const first = await repo.findAll({ pageSize: initial.pageSize });
    expect(initial.pages).toEqual(first.pages);
    expect(initial.nextAfter).toBe(first.nextAfter);
  });
});
