name: Build and Deploy client

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v1

    - name: Install dependencies
      run: bun install

    - name: Build
      run: bun run build

    - name: Install Firebase CLI
      run: bun install -g firebase-tools

    - name: Deploy to Firebase
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      run: |
        firebase use --token $FIREBASE_TOKEN
        firebase deploy --only hosting --non-interactive --token $FIREBASE_TOKEN
